### ISSUE TITLE
questions about reconnect behavior

### ISSUE THREAD

**Issue by zhammer** [furdarius/rabbitroutine#12]
hey! my team is working on a project using rabbitroutine (which has been great) and have a few questions about reconnect behavior that i can't find documentation for and can't grok from the code.

https://github.com/furdarius/rabbitroutine/blob/5d2672a7f5e9610db38fcaa4b11ef1c7d55e9384/connector.go#L19-L25

1. Is `ReconnectAttempts` the number of times rabbitroutine will attempt to reconnect to rabbit throughout the connector's lifetime or the number of times rabbitroutine will attempt to reconnect when a connection is lost
    - e.g. connection is lost and reconnects after 10 attempts, then an hour later connection is lost and reconnects after 20 attempts, max reconnects is 25 attempts, will that fail as it's a total of 10+20 total reconnect attempts?
    - i'm assuming the latter, just want to confirm
2. What is the behavior when all attempts have been exhausted?
    - we're currently just using rabbitroutine publishers, but curious about behavior on both publisher and consumer
3. What is the behavior while the connector is attempting to reconnect?
    - will `.Publish` return an err? will `.Publish` block while reconnecting?

**Comment by furdarius** [comment]
Hi @zhammer! Thank you for the good question! You are right - it's would be reasonable to add an extended description in the documentation.

Regarding your question:
1. `ReconnectAttempts` is a number that defines how many reconnect attempts would be made after the connection was broke off. After a new connection have been established this number is reset. So, when a next broke off happens there will be not less than `ReconnectAttempts` attempts to reconnect.
2. In case of *maximum reconnect attempts* exceeded* `Dial` or `DialConfig` func will just return error and that's it. It's your turn to handle this situation. But in generall it's better have unlimited `ReconnectAttemts` and log errors using [Connector.AddRetriedListener](https://pkg.go.dev/github.com/furdarius/rabbitroutine?tab=doc#Connector.AddRetriedListener) (see [Example](https://github.com/furdarius/rabbitroutine/blob/master/examples/consume/main.go#L31))
3. The question was about Publishing process during Reconnecting process. It's better to think about this 2 processes as decoupled and independent processes. So, while reconnecting is in process Publishing can't be finished, because `amqp.Channel` can't be received. But the thing is that Publisher doesn't know about the state of the connection, so for publisher it's the same as "request took too long to be finished". "Too long" is defined by `context.Context` that is passed as first argument to `Publish`. When context will be cancelled `Publish` will return the `context.DeadlineExceeded` error. If connection was reestablished and Publish had enough time to be finished, then request would be finished successfully. 

I'll add this information into docs and close the issue. Thank you for for pointing out my attention to it!

**Comment by zhammer** [comment]
thank you @furdarius ! this is great and i appreciate you adding this info into the docs

**Comment by furdarius** [comment]
Description of the reconnection behavior added: https://github.com/furdarius/rabbitroutine/pull/16
